# Generated by Django 3.1.5 on 2021-02-04 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.IntegerField(choices=[(0, 'Development'), (1, 'Administrating'), (2, 'Design'), (3, 'Management'), (4, 'Marketing'), (5, 'Popular Science')])),
                ('title', models.CharField(max_length=200)),
                ('text', django_summernote.fields.SummernoteTextField()),
                ('feed_cover', models.URLField(blank=True, null=True)),
                ('feed_article_preview', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
            },
        ),
    ]
