# Generated by Django 3.1.3 on 2020-11-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Technology'), (2, 'Development'), (3, 'Administration'), (4, 'Design'), (5, 'Business'), (6, 'Management'), (7, 'Marketing'), (8, 'Popular science')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
