# Generated by Django 3.1.3 on 2020-11-27 15:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201127_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed_article_preview',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
