# Generated by Django 3.1.3 on 2020-11-27 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201127_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed_article_preview',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
