# Generated by Django 3.1.3 on 2020-11-27 19:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201127_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed_article_preview',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
