# Generated by Django 3.1.3 on 2020-11-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_read_more_button_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='read_more_button_name',
            new_name='feed_read_more_button_name',
        ),
    ]
