# Generated by Django 3.1.3 on 2020-12-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201130_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feed_cover_caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='feed_read_more_button_name',
            field=models.CharField(blank=True, default='Read more', max_length=100, null=True),
        ),
    ]
