# Generated by Django 3.1.3 on 2020-12-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201205_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Development'), (1, 'Administrating'), (2, 'Design'), (3, 'Business'), (4, 'Management'), (5, 'Marketing'), (6, 'Popular science')]),
        ),
    ]
