# Generated by Django 3.1.3 on 2020-12-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201219_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Development'), (1, 'Administrating'), (2, 'Design'), (3, 'Management'), (4, 'Marketing'), (5, 'Popular science')]),
        ),
    ]
