# Generated by Django 3.1.3 on 2021-01-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201223_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feed_cover_caption',
        ),
    ]
