# Generated by Django 3.1.3 on 2021-01-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_feed_cover_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feed_read_more_button_name',
        ),
    ]
