# Generated by Django 3.1.5 on 2021-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210118_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'DEVELOPMENT'), (2, 'ADMINISTRATING'), (3, 'DESIGN'), (4, 'MANAGEMENT'), (5, 'MARKETING'), (6, 'POPSCI')]),
        ),
    ]
