# Generated by Django 3.2.9 on 2021-11-11 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=0, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Development'), (1, 'Administrating'), (2, 'Design'), (3, 'Management'), (4, 'Marketing'), (5, 'Popular Science')])),
                ('title', models.CharField(max_length=200)),
                ('feed_cover', models.ImageField(upload_to='blog/feed_covers')),
                ('feed_article_preview', django_summernote.fields.SummernoteTextField(blank=True)),
                ('text', django_summernote.fields.SummernoteTextField()),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ('-published',),
            },
        ),
    ]
