# Generated by Django 3.2.9 on 2021-11-24 15:58

import apps_packages.summernote.validators
from django.db import migrations, models
import django.utils.timezone
import django_summernote.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Moderated')], default=0, editable=False, verbose_name='State')),
                ('approval', models.PositiveIntegerField(blank=True, choices=[(0, 'Approved'), (1, 'Rejected')], default=None, null=True, verbose_name='Approval')),
                ('published', models.BooleanField(blank=True, default=False, verbose_name='Published')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date updated')),
                ('date_published', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date published')),
                ('is_draft', models.BooleanField(default=False, editable=False, verbose_name='Is draft')),
                ('is_pending', models.BooleanField(default=False, editable=False, verbose_name='Is pending')),
                ('is_moderated', models.BooleanField(default=False, editable=False, verbose_name='Is moderated')),
                ('is_approved', models.BooleanField(default=False, editable=False, verbose_name='Is approved')),
                ('is_rejected', models.BooleanField(default=False, editable=False, verbose_name='Is rejected')),
                ('edited_by_user', models.BooleanField(default=False, editable=False, verbose_name='Edited by user')),
                ('category', models.IntegerField(choices=[(0, 'Development'), (1, 'Administrating'), (2, 'Design'), (3, 'Management'), (4, 'Marketing'), (5, 'Popular Science')], verbose_name='Category')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('feed_cover', models.ImageField(upload_to='blog/feed_covers', verbose_name='Feed cover')),
                ('feed_article_preview', django_summernote.fields.SummernoteTextField(blank=True, null=True, verbose_name='Feed article preview')),
                ('text', django_summernote.fields.SummernoteTextField(validators=[apps_packages.summernote.validators.SummernoteMinValueValidator(500)], verbose_name='Text')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
