# Generated by Django 3.2.9 on 2021-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='approval',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Rejected'), (1, 'Approved')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Moderated')], default=1, editable=False),
        ),
    ]
