# Generated by Django 3.2.9 on 2021-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211111_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approval',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Approved'), (1, 'Rejected')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Moderated')], default=0, editable=False),
        ),
    ]
