# Generated by Django 3.2.3 on 2021-07-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='verified',
        ),
    ]
