# Generated by Django 3.2.9 on 2021-11-17 14:05

import django.core.validators
from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211117_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_summernote.fields.SummernoteTextField(validators=[django.core.validators.MinValueValidator(300)]),
        ),
    ]
