# Generated by Django 3.2.9 on 2021-11-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',), 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
