# Generated by Django 3.2.9 on 2021-11-17 15:47

import apps_packages.summernote.validators
from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_summernote.fields.SummernoteTextField(validators=[apps_packages.summernote.validators.SummernoteMinValueValidator(500)]),
        ),
    ]
