# Generated by Django 3.2.9 on 2021-11-19 10:40

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed_article_preview',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
