# Generated by Django 3.2.9 on 2021-11-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_edited_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Published'),
        ),
    ]
