# Generated by Django 3.2.9 on 2021-11-24 15:58

import apps_packages.summernote.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Moderated')], default=0, editable=False, verbose_name='State')),
                ('approval', models.PositiveIntegerField(blank=True, choices=[(0, 'Approved'), (1, 'Rejected')], default=None, null=True, verbose_name='Approval')),
                ('published', models.BooleanField(blank=True, default=False, verbose_name='Published')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date updated')),
                ('date_published', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date published')),
                ('is_draft', models.BooleanField(default=False, editable=False, verbose_name='Is draft')),
                ('is_pending', models.BooleanField(default=False, editable=False, verbose_name='Is pending')),
                ('is_moderated', models.BooleanField(default=False, editable=False, verbose_name='Is moderated')),
                ('is_approved', models.BooleanField(default=False, editable=False, verbose_name='Is approved')),
                ('is_rejected', models.BooleanField(default=False, editable=False, verbose_name='Is rejected')),
                ('edited_by_user', models.BooleanField(default=False, editable=False, verbose_name='Edited by user')),
                ('object_id', models.PositiveIntegerField(editable=False)),
                ('text', django_summernote.fields.SummernoteTextField(validators=[apps_packages.summernote.validators.SummernoteMinValueValidator(10)], verbose_name='Text')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
