# Generated by Django 3.2.9 on 2021-11-17 14:23

import apps_packages.summernote.validators
from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django_summernote.fields.SummernoteTextField(validators=[apps_packages.summernote.validators.SummernoteMinValueValidator(3)]),
        ),
    ]
