# Generated by Django 3.2.9 on 2021-11-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_alter_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
