# Generated by Django 3.2.9 on 2021-11-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.BooleanField(blank=True, default=False, verbose_name='publish'),
        ),
    ]
